# app.py
import streamlit as st
import yfinance as yf
import pandas as pd
import json
import os
from datetime import date, timedelta

# ---------------------------------------------------------
# 📊 Tamil Nadu Auto Stock Advisor — Final Version
# ---------------------------------------------------------

st.set_page_config(page_title="TN Stock Auto Advisor", layout="wide")

st.markdown(
    "<h1 style='text-align:center; color:#0066CC;'>📈 Tamil Nadu Stock Market — Auto Advisor</h1>",
    unsafe_allow_html=True,
)

st.write(
    "This app automatically analyses **all NSE/BSE stocks** every morning "
    "and selects **one best stock** expected to give the highest profit today."
)


# ---------------------------------------------------------
# 🔥 SECTION 1 — Today’s Auto Pick (from GitHub Action)
# ---------------------------------------------------------

st.header("🔥 Today’s Highest Profit Pick (Auto-Generated)")

def load_today_pick():
    """Loads today_pick.json generated by GitHub Actions."""
    try:
        if os.path.exists("today_pick.json"):
            with open("today_pick.json", "r") as f:
                return json.load(f)
        else:
            return None
    except:
        return None


pick = load_today_pick()

if pick:
    st.success(f"📌 **Best Stock to Buy Today:** {pick['ticker']}")

    st.metric(
        label="📈 Expected Profit (%) Today",
        value=f"{pick['profit']:.2f}%"
    )

    st.info(f"📝 **Reason:** {pick['reason']}")

else:
    st.warning("⏳ Today's pick not generated yet. It updates every morning by automation.")


# ---------------------------------------------------------
# 📉 SECTION 2 — Stock Chart & Live Price
# ---------------------------------------------------------

st.header("📉 View Chart for Today's Recommended Stock")

if pick:
    ticker = pick["ticker"]

    st.write(f"Loading latest data for **{ticker}**...")

    try:
        data = yf.download(ticker, period="5d", interval="1d")

        if not data.empty:
            st.line_chart(data["Close"], use_container_width=True)

            latest_price = data["Close"].iloc[-1]
            prev_price = data["Close"].iloc[-2]
            change = ((latest_price - prev_price) / prev_price) * 100

            st.metric(
                label="💰 Current Market Price",
                value=f"₹{latest_price:.2f}",
                delta=f"{change:.2f}% vs Yesterday"
            )

        else:
            st.error("No price data available for this stock.")

    except Exception as e:
        st.error("Failed to load chart or price.")
        st.text(str(e))

else:
    st.info("Waiting for daily pick…")


# ---------------------------------------------------------
# 📊 SECTION 3 — Show Ranked Best Stocks List
# ---------------------------------------------------------

st.header("📊 Full Ranked Candidate List")

def load_candidate_list():
    if os.path.exists("candidates.csv"):
        try:
            return pd.read_csv("candidates.csv")
        except:
            return None
    return None


df = load_candidate_list()

if df is not None:
    st.dataframe(df, use_container_width=True)
else:
    st.info("Candidates list will appear after daily run.")


# ---------------------------------------------------------
# Footer
# ---------------------------------------------------------

st.caption("Data auto-updated daily using GitHub Actions. Powered by Yahoo Finance.")
            
