# app.py
import streamlit as st
import yfinance as yf
import pandas as pd
import json
import os
from datetime import date, timedelta

# ---------------------------------------------------------
# 📊 Tamil Nadu Auto Stock Advisor — Final Version
# ---------------------------------------------------------

st.set_page_config(page_title="TN Stock Auto Advisor", layout="wide")

st.markdown(
    "<h1 style='text-align:center; color:#0066CC;'>📈 Tamil Nadu Stock Market — Auto Advisor</h1>",
    unsafe_allow_html=True,
)

st.write(
    "This app automatically analyses **all NSE/BSE stocks** every morning "
    "and selects **one best stock** expected to give the highest profit today."
)


# ---------------------------------------------------------
# 🔥 SECTION 1 — Today’s Auto Pick (from GitHub Action)
# ---------------------------------------------------------

st.header("🔥 Today’s Highest Profit Pick (Auto-Generated)")

def load_today_pick():
    """Loads today_pick.json generated by GitHub Actions."""
    try:
        if os.path.exists("today_pick.json"):
            with open("today_pick.json", "r") as f:
                return json.load(f)
        else:
            return None
    except:
        return None


pick = load_today_pick()

if pick:
    st.success(f"📌 **Best Stock to Buy Today:** {pick['ticker']}")

    # --- Safe profit display: handle missing or different JSON keys ---
# Try common keys in today_pick.json: profit OR compute from price/buy_price if available

profit = None

# 1) direct key if present
if isinstance(pick, dict):
    profit = pick.get("profit") or pick.get("estimated_profit") or pick.get("expected_profit")

# 2) if not present, try compute from known fields (price & buy_price)
if profit is None:
    # support older JSON shapes: {"ticker"/"symbol","price"/"buy_price"}
    buy_price = pick.get("buy_price") or pick.get("price") or pick.get("entry_price")
    current_price = pick.get("current_price") or pick.get("price") or None
    # if we have buy_price and current_price compute a simple percent (best-effort)
    try:
        if buy_price is not None and current_price is not None:
            profit = ((float(current_price) - float(buy_price)) / float(buy_price)) * 100
    except Exception:
        profit = None

# 3) show metric (N/A when not available)
if profit is None:
    st.metric(label="Estimated Profit (%)", value="N/A")
else:
    st.metric(label="Estimated Profit (%)", value=f"{float(profit):.2f}%")"
    )

    st.info(f"📝 **Reason:** {pick['reason']}")

else:
    st.warning("⏳ Today's pick not generated yet. It updates every morning by automation.")


# ---------------------------------------------------------
# 📉 SECTION 2 — Stock Chart & Live Price
# ---------------------------------------------------------

st.header("📉 View Chart for Today's Recommended Stock")

if pick:
    ticker = pick["ticker"]

    st.write(f"Loading latest data for **{ticker}**...")

    try:
        data = yf.download(ticker, period="5d", interval="1d")

        if not data.empty:
            st.line_chart(data["Close"], use_container_width=True)

            latest_price = data["Close"].iloc[-1]
            prev_price = data["Close"].iloc[-2]
            change = ((latest_price - prev_price) / prev_price) * 100

            st.metric(
                label="💰 Current Market Price",
                value=f"₹{latest_price:.2f}",
                delta=f"{change:.2f}% vs Yesterday"
            )

        else:
            st.error("No price data available for this stock.")

    except Exception as e:
        st.error("Failed to load chart or price.")
        st.text(str(e))

else:
    st.info("Waiting for daily pick…")


# ---------------------------------------------------------
# 📊 SECTION 3 — Show Ranked Best Stocks List
# ---------------------------------------------------------

st.header("📊 Full Ranked Candidate List")

def load_candidate_list():
    if os.path.exists("candidates.csv"):
        try:
            return pd.read_csv("candidates.csv")
        except:
            return None
    return None


df = load_candidate_list()

if df is not None:
    st.dataframe(df, use_container_width=True)
else:
    st.info("Candidates list will appear after daily run.")


# ---------------------------------------------------------
# Footer
# ---------------------------------------------------------

st.caption("Data auto-updated daily using GitHub Actions. Powered by Yahoo Finance.")
            
